---
title: "HM5 final figures"
author: "Jessica Gronniger"
date: "2022-12-01"
output: html_document
---

```{r, echo=FALSE, message=FALSE,  warning=FALSE}

library(ggplot2)
library(tidyverse)
library(scales)
library(dplyr)
library(vegan)
library(RColorBrewer)
library(gghighlight)
library(egg)
library(gridExtra)
```

```{r, echo=FALSE}


distenv2 = read.csv("~/Desktop/HM5_figure_files/PICO_noHurr_clean.csv", header=TRUE)

distenv <- read.csv("~/Desktop/PICO_all_clean.csv", header=T)

florence=distenv[366:475,]

```

###Figure showing chla, salinity and DOC after florence relative to average PICO concentrations 
```{r}



chloro=ggplot(distenv2, aes(x = YearDay, y = Chloro))+ 
  geom_point(alpha=0.1, color="forestgreen")  +theme_bw()+
  geom_line(data=florence, aes(x=YearDay, y=Chloro), color="forestgreen") + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14)) +
  geom_smooth(data=distenv2, color="black", method="loess",span=0.2, size=0.5, level=0.95) + ylab("Chl a (mg/L)") + xlim(200, 365)+ geom_vline(xintercept=256) 

doc=ggplot(distenv2, aes(x = YearDay, y = DOC))+ 
  geom_point(alpha=0.1) +theme_bw()+
  geom_line(data=florence, aes(x=YearDay, y=DOC), color="maroon") + 
theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14)) +
  geom_smooth(data=distenv2, color="black", method="loess",span=0.2, size=0.5, level=0.95) + ylab("DOC (uM)") + xlim(200, 365)+ geom_vline(xintercept=256)

sal = ggplot(distenv2, aes(x = YearDay, y = Salinity))+ 
  geom_point(alpha=0.1, color="blue")  + theme_bw()+
  geom_line(data=florence, aes(x=YearDay, y=Salinity), color="blue") + 
 theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14)) +
  geom_smooth(data=distenv2, color="black", method="loess",span=0.2, size=0.5, level=0.95) + ylab("Salinity (PSU)") + xlim(200, 365)+ geom_vline(xintercept=256)


```

```{r}




chist = ggplot(distenv, aes(x=Chloro)) + 
  geom_density() +coord_flip()+ theme_bw()+
 theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14))

shist = ggplot(distenv, aes(x=Salinity)) + 
  geom_density() +coord_flip()+ theme_bw()+
 theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14))

dhist = ggplot(distenv, aes(x=DOC)) + 
  geom_density() +coord_flip()+ theme_bw()+
 theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14))

svg("~/Desktop/HM5_hurricane_env_density.svg", width=16, height =12)
ggarrange(shist, sal, chist, chloro, dhist, doc,
          
          ncol = 2, nrow = 3, widths = c(0.25, 1))
dev.off()
```


```{r}
svg("~/Desktop/HM_env_faceted_nohur.svg", height= 20, width=16)
ggarrange( sal, chloro,doc, 
          labels = c("A", "B", "C"),
          ncol = 1, nrow = 3, align="hv")

dev.off()
``` 


##Figure of FCM data over time by treatment
```{r}

hm5_meta = read.csv("~/HM5_figure_files/HM5_metadata.csv", header=T)

hmfcm = read.csv("~/HM5_figure_files/HM5_FCM_data.csv", header=T)

```



```{r}
syn = ggplot(hmfcm, aes(x = Day, y = Syn)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Log(Synechococcus)") + 
  geom_errorbar(aes(ymin=Syn-SynSD, ymax=Syn+SynSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14), axis.title = element_text(size=14),
          axis.text.y = element_text(size=14), legend.key.size = unit(2, 'cm'), legend.title = element_text(size=14), legend.text = element_text(size=12)) + geom_hline(yintercept=4.41, color="black", linetype="dashed")

peuks = ggplot(hmfcm, aes(x = Day, y = Peuks)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Log(Picoeukaryotes)") + 
  geom_errorbar(aes(ymin=Peuks-PeuksSD, ymax=Peuks+PeuksSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14),axis.title = element_text(size=14),
          axis.text.y = element_text(size=14), legend.key.size = unit(2, 'cm'), legend.title = element_text(14), legend.text = element_text(size=12))+ geom_hline(yintercept=3.16, color="black", linetype="dashed")

cyano = ggplot(hmfcm, aes(x = Day, y = Picocyano)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Log(Picocyanobacteria)") + 
  geom_errorbar(aes(ymin=Picocyano-PicocyanoSD, ymax=Picocyano+PicocyanoSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14),axis.title = element_text(size=14),
          axis.text.y = element_text(size=14), legend.key.size = unit(2, 'cm'), legend.title = element_text(size=14), legend.text = element_text(size=12)) + geom_hline(yintercept=3.85, color="black", linetype="dashed")

bac = ggplot(hmfcm, aes(x = Day, y = Bacteria)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Log(Bacteria)") + 
  geom_errorbar(aes(ymin=Bacteria-BacteriaSD, ymax=Bacteria+BacteriaSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=14),axis.title = element_text(size=14),
          axis.text.y = element_text(size=14), legend.key.size = unit(2, 'cm'), legend.title = element_text(size=14), legend.text = element_text(size=12))+ geom_hline(yintercept=5.33, color="black", linetype="dashed")
```

```{r}
library(ggpubr)
svg("~/Desktop/HM5_FCM.svg", height=8, width=14)
ggarrange( syn, cyano,peuks,bac, 
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2, common.legend=TRUE)

dev.off()

```

##Line plots of chlorophyll, doc, and BOD over time
```{r}

hmenv = read.csv("~/HM5_figure_files/HM5_env.csv", header=T)

```

```{r}


bod = hmenv[c(1:3, 10:12, 16:18),]

```

```{r}
chl = ggplot(hmenv, aes(x = Day, y = ChlAvg)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Chla") + 
  geom_errorbar(aes(ymin=ChlAvg-ChlSD, ymax=ChlAvg+ChlSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12))

doc = ggplot(bod, aes(x = Day, y = DOCavg)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("DOC") + 
  geom_errorbar(aes(ymin=DOCavg-DOCsd, ymax=DOCavg+DOCsd), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12))

resp = ggplot(bod, aes(x = Day, y = ResAvg)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Repiration") + 
  geom_errorbar(aes(ymin=ResAvg-ResSD, ymax=ResAvg+ResSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12))

grossphoto = ggplot(bod, aes(x = Day, y = PhotoAvg)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Photosynthesis") + 
  geom_errorbar(aes(ymin=PhotoAvg-PhotoSD, ymax=PhotoAvg+PhotoSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12))

netprod = ggplot(bod, aes(x = Day, y = ProdAvg)) + 
  geom_line(aes(color = Treatment))+
  scale_color_manual(values = c("darkred", "blue", "forestgreen")) +
   geom_point()+ ylab("Productivity") + 
  geom_errorbar(aes(ymin=ProdAvg-ProdSD, ymax=ProdAvg+ProdSD), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12))


```

```{r}
library(ggpubr)
svg("~/Desktop/HM5_env.svg", height=12, width=14)
ggarrange(chl, doc,resp,grossphoto, netprod,
          labels = c("A", "B", "C", "D", "E"),
          ncol = 2, nrow = 3, common.legend=TRUE, legend="bottom")

dev.off()

```

###Plot of DESeq log2FC
```{r}
#heatmap of responding taxa
library("vegan")
library("RColorBrewer")
library("reshape2")
library("ggplot2")
library("gplots")
library("gridExtra")
library("ellipse")
library("heatmap.plus")
library("DESeq2")
```


```{r}
domresults <- read.csv('~/Desktop/HM5_dom_sigresults.csv', header=T)

domresults$ASV <- factor(domresults$ASV, levels = domresults$ASV[order(domresults$Order)])
domresults$ASV  # notice the changed order of factor levels

dom=ggplot(domresults, aes(x = as.factor(ASV), y = log2FoldChange)) + 
   geom_point(aes(color=factor(sign(log2FoldChange)))) +
 scale_color_manual(values = c("blue", "black", "red"),
                     breaks = c("-1", "0", "1"))+  
  geom_errorbar(aes(ymin=log2FoldChange-lfcSE, ymax=log2FoldChange+lfcSE), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme( panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12), panel.border = element_rect(colour = "black", fill=NA, size=1), legend.position="none")+ coord_flip()

```

```{r}
dilresults <- read.csv('~/Desktop/HM5_dil_sigresults.csv', header=T)

dilresults$ASV <- factor(dilresults$ASV, levels = dilresults$ASV[order(dilresults$Order)])
dilresults$ASV  # notice the changed order of factor levels

dil = ggplot(dilresults, aes(x = as.factor(ASV), y = log2FoldChange)) + 
   geom_point(aes(color=factor(sign(log2FoldChange)))) +
 scale_color_manual(values = c("blue", "black", "red"),
                     breaks = c("-1", "0", "1"))+  
  geom_errorbar(aes(ymin=log2FoldChange-lfcSE, ymax=log2FoldChange+lfcSE), width=.1,
                 position=position_dodge(0.05))+ theme_bw()+
  theme( panel.grid.major = element_blank(),panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(size=12),
          axis.text.y = element_text(size=12), panel.border = element_rect(colour = "black", fill=NA, size=1), legend.position="none")+ coord_flip()

```


```{r}

svg("~/Desktop/HM5_deseq_scatterplot.svg", height=8, width=12)
ggarrange(dil, dom, labels=c("A", "B"), nrow=1, ncol=2)
dev.off()
```




##Boxplots of diversity metrics by cluster
```{r}
swasv = read.csv("~/Desktop/SW_final_data/SW_ASV_relab.csv", check.names=F)
swmeta=read.csv("~/Desktop/SW_final_data/SW_DNA_meta.csv")

swdata=merge(swasv, swmeta, by="Sample")
```

```{r}
# Shannon's H'
H <- diversity(swdata[,2:5062])

# Observed Richness
richness <- specnumber(swdata[,2:5062])  

# Pielou's Evenness
evenness <- H/log(richness)
  
# Create alpha diversity dataframe including environmental data
alpha <- cbind(shannon = H, richness = richness, pielou = evenness, swmeta)
head(alpha)
```
```{r}

my_comparisons <- list( c("K1", "K2"), c("K1", "K3"), c("K1", "K4"), c("K2", "K3"), c("K2", "K4"), c("K3", "K4") )

compare_means(shannon ~ kcluster4,  data = alpha, p.adjust.method = "bonferroni")
plot.shan <- ggplot(alpha, aes(x = kcluster4, y = shannon, colour = kcluster4)) +
  geom_boxplot(size = 1) +
  scale_color_manual(values = c("K1" = "#006600", "K2" = "#00CC00", "K3" = "#0000CC", "K4" = "#3399FF")) +
  ylab("Shannon's H'") + 
  xlab("") +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  stat_compare_means(comparisons=my_comparisons) 

compare_means(richness ~ kcluster4,  data = alpha, p.adjust.method = "bonferroni")
plot.rich <-ggplot(alpha, aes(x = kcluster4, y = richness, colour = kcluster4)) +
  geom_boxplot(size = 1) +
  scale_color_manual(values = c("K1" = "#006600", "K2" = "#00CC00", "K3" = "#0000CC", "K4" = "#3399FF")) +
  ylab("Species Richness") +
  xlab("") +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
  stat_compare_means(comparisons=my_comparisons) 

compare_means(pielou ~ kcluster4,  data = alpha, p.adjust.method = "bonferroni")
plot.even <- ggplot(alpha, aes(x = kcluster4, y = pielou, colour = kcluster4)) +
  geom_boxplot(size = 1) +
  scale_color_manual(values = c("K1" = "#006600", "K2" = "#00CC00", "K3" = "#0000CC", "K4" = "#3399FF")) +
  ylab("Pielou's Evenness") +
  xlab("") +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  stat_compare_means(comparisons=my_comparisons) 

legend <- get_legend(plot.even)

```
```{r}
svg("~/Desktop/SW_richness.svg", height=4, width=10)
plot_grid(plot.shan + theme(legend.position = "none"), plot.rich + theme(legend.position = "none"), plot.even + theme(legend.position = "none"),ncol = 3)
dev.off()
```